version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=suJHohY49R37cZAbuV9YVik1ifbv+qroSNAEuDCqQN9xK7F9Y+FA2KmVgyudhy8eTvFzaccuIUhogqS5JHDm3w==
      - JWT_SECRET_KEY=suJHohY49R37cZAbuV9YVik1ifbv+qroSNAEuDCqQN9xK7F9Y+FA2KmVgyudhy8eTvFzaccuIUhogqS5JHDm3w==
      - DATABASE_URL=mysql+pymysql://root:@db/auth_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  